"""Multi-Strategy Confluence Analyzer.

Requires multiple strategies to agree before executing a trade. When multiple
independent strategies generate signals in the same direction, confidence
increases significantly.

Usage:
    from src.research.multi_strategy import (
        StrategyConfluenceAnalyzer,
        StrategySignal,
        ConfluenceLevel,
        ConfluenceResult,
    )

    analyzer = StrategyConfluenceAnalyzer(min_confluence_level=ConfluenceLevel.WEAK)

    # Register strategies with performance weights
    analyzer.register_strategy("ema_crossover", performance_score=1.2)
    analyzer.register_strategy("rsi_reversal", performance_score=0.9)

    # Add signals as they come
    analyzer.add_signal(StrategySignal(
        strategy_name="ema_crossover",
        signal_type="BUY_CE",
        confidence=75,
        underlying="NIFTY"
    ))

    # Check confluence before trading
    result = analyzer.analyze_confluence("NIFTY", "BUY_CE")
    if result.level >= ConfluenceLevel.MODERATE:
        execute_trade()  # High confidence
    elif result.level == ConfluenceLevel.WEAK:
        reduce_position_size()  # Caution
    else:
        skip_trade()  # No confluence
"""

from __future__ import annotations

import threading
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Optional

from loguru import logger


class ConfluenceLevel(Enum):
    """Confluence level based on number of agreeing strategies.

    Attributes:
        NONE: Single strategy only (no confluence)
        WEAK: 2 strategies agree
        MODERATE: 3 strategies agree
        STRONG: 4+ strategies agree
        CONFLICT: Strategies disagree (conflicting signals)
    """

    NONE = 0
    WEAK = 1
    MODERATE = 2
    STRONG = 3
    CONFLICT = -1


class StrategyCategory(Enum):
    """Category of strategy for diversity scoring.

    Attributes:
        TREND: Trend-following strategies (e.g., EMA crossover, Supertrend)
        MOMENTUM: Momentum-based strategies (e.g., MACD, RSI extremes)
        MEAN_REVERSION: Mean reversion strategies (e.g., RSI reversal, Bollinger Bands)
        VOLATILITY: Volatility-based strategies (e.g., ATR breakout)
        PATTERN: Pattern-based strategies (e.g., candlestick patterns)
    """

    TREND = "trend"
    MOMENTUM = "momentum"
    MEAN_REVERSION = "mean_reversion"
    VOLATILITY = "volatility"
    PATTERN = "pattern"
    UNKNOWN = "unknown"


@dataclass
class StrategySignal:
    """A signal generated by a strategy.

    All monetary values are in PAISA (integer) - 1 Rupee = 100 paisa.
    All timestamps are in IST (Asia/Kolkata).

    Attributes:
        strategy_name: Name of the strategy that generated this signal
        signal_type: Type of signal (BUY_CE, BUY_PE, BUY, SELL)
        confidence: Confidence score 0-100
        timestamp: When the signal was generated
        underlying: Underlying symbol (e.g., "NIFTY", "RELIANCE")
        entry_price: Optional entry price in paisa
        stop_loss: Optional stop loss in paisa
        target: Optional target price in paisa
    """

    strategy_name: str
    signal_type: str  # BUY_CE, BUY_PE, BUY, SELL
    confidence: float
    timestamp: datetime
    underlying: str
    entry_price: Optional[int] = None  # paisa
    stop_loss: Optional[int] = None  # paisa
    target: Optional[int] = None  # paisa

    def __post_init__(self):
        """Validate signal after initialization."""
        if not 0 <= self.confidence <= 100:
            raise ValueError(f"Confidence must be 0-100, got {self.confidence}")
        if self.signal_type not in ("BUY_CE", "BUY_PE", "BUY", "SELL"):
            raise ValueError(f"Invalid signal_type: {self.signal_type}")


@dataclass
class ConfluenceResult:
    """Result of confluence analysis.

    Attributes:
        level: Confluence level (NONE, WEAK, MODERATE, STRONG, CONFLICT)
        score: Overall confluence score 0-100
        agreeing_strategies: List of strategy names that agree
        conflicting_strategies: List of strategy names that conflict
        weighted_confidence: Confidence weighted by strategy performance
        recommendation: EXECUTE, REDUCE_SIZE, or SKIP
        details: Additional analysis details
    """

    level: ConfluenceLevel
    score: float  # 0-100
    agreeing_strategies: list[str] = field(default_factory=list)
    conflicting_strategies: list[str] = field(default_factory=list)
    weighted_confidence: float = 0.0
    recommendation: str = "SKIP"  # EXECUTE, REDUCE_SIZE, or SKIP
    details: dict = field(default_factory=dict)

    def __post_init__(self):
        """Ensure score is within bounds."""
        self.score = max(0, min(100, self.score))


@dataclass
class StrategyInfo:
    """Information about a registered strategy.

    Attributes:
        name: Strategy name
        performance_score: Weight based on historical performance (default 1.0)
        win_rate: Historical win rate 0-1
        profit_factor: Historical profit factor
        category: Strategy category for diversity scoring
        last_updated: When performance was last updated
    """

    name: str
    performance_score: float = 1.0
    win_rate: float = 0.5
    profit_factor: float = 1.0
    category: StrategyCategory = StrategyCategory.UNKNOWN
    last_updated: datetime = field(default_factory=datetime.now)


class StrategyConfluenceAnalyzer:
    """Analyzes confluence between multiple strategy signals.

    This class tracks signals from multiple strategies and calculates
    a confluence score based on agreement level, strategy performance,
    and signal diversity.

    Thread-safe for concurrent signal addition and analysis.

    Example:
        analyzer = StrategyConfluenceAnalyzer(
            min_confluence_level=ConfluenceLevel.WEAK
        )

        # Register strategies
        analyzer.register_strategy("ema_crossover", performance_score=1.2)
        analyzer.register_strategy("rsi_reversal", performance_score=0.9)

        # Add signals
        analyzer.add_signal(StrategySignal(
            strategy_name="ema_crossover",
            signal_type="BUY_CE",
            confidence=75,
            underlying="NIFTY"
        ))

        # Analyze
        result = analyzer.analyze_confluence("NIFTY", "BUY_CE")
        if result.recommendation == "EXECUTE":
            # Proceed with trade
            pass
    """

    # Strategy name to category mapping (can be extended)
    STRATEGY_CATEGORIES: dict[str, StrategyCategory] = {
        # Trend strategies
        "ema_crossover": StrategyCategory.TREND,
        "sma_crossover": StrategyCategory.TREND,
        "supertrend": StrategyCategory.TREND,
        "adx_trend": StrategyCategory.TREND,
        # Momentum strategies
        "macd_momentum": StrategyCategory.MOMENTUM,
        "rsi_momentum": StrategyCategory.MOMENTUM,
        "stochastic_momentum": StrategyCategory.MOMENTUM,
        # Mean reversion strategies
        "rsi_reversal": StrategyCategory.MEAN_REVERSION,
        "rsi_mean_reversion": StrategyCategory.MEAN_REVERSION,
        "bollinger_reversal": StrategyCategory.MEAN_REVERSION,
        # Volatility strategies
        "vwap_breakout": StrategyCategory.VOLATILITY,
        "atr_breakout": StrategyCategory.VOLATILITY,
        # Pattern strategies
        "candlestick_pattern": StrategyCategory.PATTERN,
        "chart_pattern": StrategyCategory.PATTERN,
    }

    def __init__(
        self,
        min_confluence_level: ConfluenceLevel = ConfluenceLevel.WEAK,
        max_signal_buffer_size: int = 100,
        signal_expiry_seconds: int = 300,
    ):
        """Initialize the confluence analyzer.

        Args:
            min_confluence_level: Minimum confluence level required for trading
            max_signal_buffer_size: Maximum number of signals to keep in buffer
            signal_expiry_seconds: Signals older than this are considered expired
        """
        self.min_confluence_level = min_confluence_level
        self.max_signal_buffer_size = max_signal_buffer_size
        self.signal_expiry_seconds = signal_expiry_seconds

        # Registered strategies with their weights
        self._strategies: dict[str, StrategyInfo] = {}

        # Signal buffer: list of StrategySignal
        self._signals: list[StrategySignal] = []

        # Thread safety
        self._lock = threading.RLock()

        logger.info(
            f"StrategyConfluenceAnalyzer initialized "
            f"(min_level={min_confluence_level.name}, "
            f"max_buffer={max_signal_buffer_size})"
        )

    def register_strategy(
        self,
        name: str,
        performance_score: float = 1.0,
        win_rate: float = 0.5,
        profit_factor: float = 1.0,
        category: Optional[StrategyCategory] = None,
    ) -> None:
        """Register a strategy with performance weighting.

        Args:
            name: Unique strategy name
            performance_score: Weight based on performance (default 1.0)
            win_rate: Historical win rate 0-1
            profit_factor: Historical profit factor
            category: Strategy category for diversity scoring
        """
        with self._lock:
            # Auto-detect category if not provided
            if category is None:
                category = self.STRATEGY_CATEGORIES.get(
                    name, StrategyCategory.UNKNOWN
                )

            self._strategies[name] = StrategyInfo(
                name=name,
                performance_score=max(0.1, performance_score),  # Min 0.1
                win_rate=max(0, min(1, win_rate)),
                profit_factor=max(0.1, profit_factor),
                category=category,
                last_updated=datetime.now(),
            )
            logger.debug(f"Registered strategy: {name} (score={performance_score:.2f})")

    def unregister_strategy(self, name: str) -> None:
        """Unregister a strategy.

        Args:
            name: Strategy name to unregister
        """
        with self._lock:
            if name in self._strategies:
                del self._strategies[name]
                logger.debug(f"Unregistered strategy: {name}")

    def add_signal(self, signal: StrategySignal) -> None:
        """Add a new signal to the buffer.

        Args:
            signal: StrategySignal to add

        Raises:
            ValueError: If strategy is not registered
        """
        with self._lock:
            if signal.strategy_name not in self._strategies:
                # Auto-register with default values
                self.register_strategy(signal.strategy_name)

            # Add signal
            self._signals.append(signal)

            # Maintain buffer size limit
            if len(self._signals) > self.max_signal_buffer_size:
                self._signals.pop(0)

            logger.debug(
                f"Added signal: {signal.strategy_name} -> {signal.signal_type} "
                f"({signal.underlying}, conf={signal.confidence:.1f})"
            )

    def clear_expired_signals(self, max_age_seconds: Optional[int] = None) -> int:
        """Remove signals older than specified age.

        Args:
            max_age_seconds: Maximum age in seconds (default: self.signal_expiry_seconds)

        Returns:
            Number of signals removed
        """
        max_age = max_age_seconds or self.signal_expiry_seconds
        cutoff_time = datetime.now() - timedelta(seconds=max_age)

        with self._lock:
            original_count = len(self._signals)
            self._signals = [
                s for s in self._signals if s.timestamp >= cutoff_time
            ]
            removed = original_count - len(self._signals)

            if removed > 0:
                logger.debug(f"Cleared {removed} expired signals (age > {max_age}s)")

            return removed

    def clear_all_signals(self) -> None:
        """Clear all signals from buffer."""
        with self._lock:
            count = len(self._signals)
            self._signals.clear()
            logger.debug(f"Cleared all {count} signals")

    def get_signals_for_underlying(
        self, underlying: str, direction: Optional[str] = None
    ) -> list[StrategySignal]:
        """Get all signals for a specific underlying.

        Args:
            underlying: Underlying symbol
            direction: Optional filter by signal direction

        Returns:
            List of matching signals
        """
        with self._lock:
            signals = [
                s for s in self._signals
                if s.underlying == underlying
            ]
            if direction:
                signals = [s for s in signals if s.signal_type == direction]
            return signals

    def analyze_confluence(
        self, underlying: str, direction: str
    ) -> ConfluenceResult:
        """Analyze confluence for a specific underlying and direction.

        Args:
            underlying: Underlying symbol (e.g., "NIFTY")
            direction: Signal direction (e.g., "BUY_CE", "BUY_PE", "BUY", "SELL")

        Returns:
            ConfluenceResult with analysis details
        """
        with self._lock:
            # Clear expired signals first
            self.clear_expired_signals()

            # Get relevant signals
            agreeing_signals = []
            conflicting_signals = []

            for signal in self._signals:
                if signal.underlying != underlying:
                    continue

                if signal.signal_type == direction:
                    agreeing_signals.append(signal)
                elif self._is_conflicting(signal.signal_type, direction):
                    conflicting_signals.append(signal)

            # Calculate confluence
            return self._calculate_confluence(
                underlying, direction, agreeing_signals, conflicting_signals
            )

    def get_confluence_for_signal(self, signal: StrategySignal) -> ConfluenceResult:
        """Get confluence analysis for a specific signal.

        Args:
            signal: The signal to analyze

        Returns:
            ConfluenceResult for this signal
        """
        return self.analyze_confluence(signal.underlying, signal.signal_type)

    def update_strategy_performance(
        self,
        name: str,
        win_rate: float,
        profit_factor: float,
    ) -> None:
        """Update strategy performance metrics.

        Args:
            name: Strategy name
            win_rate: Historical win rate 0-1
            profit_factor: Historical profit factor

        Raises:
            ValueError: If strategy not registered
        """
        with self._lock:
            if name not in self._strategies:
                raise ValueError(f"Strategy not registered: {name}")

            info = self._strategies[name]
            info.win_rate = max(0, min(1, win_rate))
            info.profit_factor = max(0.1, profit_factor)

            # Update performance score based on win rate and profit factor
            # Formula: (win_rate * 0.4 + normalized_pf * 0.6) * 2
            # normalized_pf = profit_factor / (profit_factor + 1) -> 0-1 range
            normalized_pf = profit_factor / (profit_factor + 1)
            info.performance_score = (win_rate * 0.4 + normalized_pf * 0.6) * 2
            info.last_updated = datetime.now()

            logger.debug(
                f"Updated {name}: win_rate={win_rate:.2%}, "
                f"pf={profit_factor:.2f}, score={info.performance_score:.2f}"
            )

    def get_registered_strategies(self) -> dict[str, StrategyInfo]:
        """Get all registered strategies.

        Returns:
            Dictionary of strategy name -> StrategyInfo
        """
        with self._lock:
            return dict(self._strategies)

    def get_signal_count(self) -> int:
        """Get current number of signals in buffer.

        Returns:
            Number of signals
        """
        with self._lock:
            return len(self._signals)

    def _is_conflicting(self, signal_type1: str, signal_type2: str) -> bool:
        """Check if two signal types conflict.

        Args:
            signal_type1: First signal type
            signal_type2: Second signal type

        Returns:
            True if signals conflict
        """
        # Define conflicting pairs
        buy_types = {"BUY", "BUY_CE", "BUY_PE"}
        sell_types = {"SELL"}

        s1_in_buy = signal_type1 in buy_types
        s2_in_buy = signal_type2 in buy_types
        s1_in_sell = signal_type1 in sell_types
        s2_in_sell = signal_type2 in sell_types

        # BUY vs SELL conflicts
        if (s1_in_buy and s2_in_sell) or (s1_in_sell and s2_in_buy):
            return True

        # BUY_CE vs BUY_PE conflicts (different directions)
        if (signal_type1 == "BUY_CE" and signal_type2 == "BUY_PE") or \
           (signal_type1 == "BUY_PE" and signal_type2 == "BUY_CE"):
            return True

        return False

    def _calculate_confluence(
        self,
        underlying: str,
        direction: str,
        agreeing_signals: list[StrategySignal],
        conflicting_signals: list[StrategySignal],
    ) -> ConfluenceResult:
        """Calculate confluence score and level.

        Args:
            underlying: Underlying symbol
            direction: Signal direction
            agreeing_signals: List of agreeing signals
            conflicting_signals: List of conflicting signals

        Returns:
            ConfluenceResult
        """
        agreeing_count = len(agreeing_signals)
        conflicting_count = len(conflicting_signals)

        # Get unique strategies
        agreeing_strategies = list(set(s.strategy_name for s in agreeing_signals))
        conflicting_strategies = list(set(s.strategy_name for s in conflicting_signals))

        # Determine confluence level
        if conflicting_count > 0 and agreeing_count <= 1:
            level = ConfluenceLevel.CONFLICT
        elif agreeing_count >= 4:
            level = ConfluenceLevel.STRONG
        elif agreeing_count == 3:
            level = ConfluenceLevel.MODERATE
        elif agreeing_count == 2:
            level = ConfluenceLevel.WEAK
        else:
            level = ConfluenceLevel.NONE

        # Calculate weighted confidence
        weighted_confidence = self._calculate_weighted_confidence(agreeing_signals)

        # Calculate diversity bonus
        diversity_bonus = self._calculate_diversity_bonus(agreeing_signals)

        # Calculate base score
        base_score = min(agreeing_count * 25, 75)  # 2=50, 3=75, 4+=75

        # Performance bonus
        performance_bonus = sum(
            self._strategies.get(s.strategy_name, StrategyInfo(s.strategy_name)).performance_score
            for s in agreeing_signals
        ) * 2.5  # Scale to reasonable range
        performance_bonus = min(performance_bonus, 15)  # Cap at 15

        # Conflict penalty
        conflict_penalty = conflicting_count * 15

        # Time decay factor (newer signals count more)
        time_factor = self._calculate_time_factor(agreeing_signals)

        # Final score
        score = (
            base_score * time_factor +
            performance_bonus +
            diversity_bonus -
            conflict_penalty
        )
        score = max(0, min(100, score))

        # Determine recommendation
        recommendation = self._determine_recommendation(level, score, conflicting_count)

        # Build details
        details = {
            "base_score": base_score,
            "performance_bonus": performance_bonus,
            "diversity_bonus": diversity_bonus,
            "conflict_penalty": conflict_penalty,
            "time_factor": time_factor,
            "agreeing_count": agreeing_count,
            "conflicting_count": conflicting_count,
            "unique_categories": diversity_bonus // 5,
        }

        return ConfluenceResult(
            level=level,
            score=score,
            agreeing_strategies=agreeing_strategies,
            conflicting_strategies=conflicting_strategies,
            weighted_confidence=weighted_confidence,
            recommendation=recommendation,
            details=details,
        )

    def _calculate_weighted_confidence(
        self, signals: list[StrategySignal]
    ) -> float:
        """Calculate confidence weighted by strategy performance.

        Args:
            signals: List of signals

        Returns:
            Weighted confidence score 0-100
        """
        if not signals:
            return 0.0

        total_weight = 0.0
        weighted_sum = 0.0

        for signal in signals:
            info = self._strategies.get(
                signal.strategy_name, StrategyInfo(signal.strategy_name)
            )
            weight = info.performance_score
            weighted_sum += signal.confidence * weight
            total_weight += weight

        if total_weight == 0:
            return 0.0

        return weighted_sum / total_weight

    def _calculate_diversity_bonus(self, signals: list[StrategySignal]) -> float:
        """Calculate bonus for diverse strategy types.

        Args:
            signals: List of signals

        Returns:
            Diversity bonus 0-15
        """
        categories: set[StrategyCategory] = set()

        for signal in signals:
            info = self._strategies.get(
                signal.strategy_name, StrategyInfo(signal.strategy_name)
            )
            categories.add(info.category)

        # Remove UNKNOWN from count
        categories.discard(StrategyCategory.UNKNOWN)

        # 5 points per unique category, max 15
        return min(len(categories) * 5, 15)

    def _calculate_time_factor(self, signals: list[StrategySignal]) -> float:
        """Calculate time decay factor for signals.

        Newer signals count more. Signals older than expiry time count less.

        Args:
            signals: List of signals

        Returns:
            Time factor 0.5-1.0
        """
        if not signals:
            return 1.0

        now = datetime.now()
        total_weight = 0.0

        for signal in signals:
            age_seconds = (now - signal.timestamp).total_seconds()
            # Linear decay: 1.0 at t=0, 0.5 at t=expiry
            decay = max(0.5, 1.0 - (age_seconds / (self.signal_expiry_seconds * 2)))
            total_weight += decay

        avg_weight = total_weight / len(signals)
        return avg_weight

    def _determine_recommendation(
        self, level: ConfluenceLevel, score: float, conflict_count: int
    ) -> str:
        """Determine trading recommendation based on confluence.

        Args:
            level: Confluence level
            score: Confluence score
            conflict_count: Number of conflicting signals

        Returns:
            "EXECUTE", "REDUCE_SIZE", or "SKIP"
        """
        # Strong conflicts always skip
        if conflict_count >= 2 and level in (ConfluenceLevel.NONE, ConfluenceLevel.WEAK):
            return "SKIP"

        # Conflict level always skip unless very strong agreement
        if level == ConfluenceLevel.CONFLICT:
            return "SKIP"

        # Below minimum confluence level
        if level.value < self.min_confluence_level.value:
            return "SKIP"

        # Strong confluence always execute
        if level == ConfluenceLevel.STRONG:
            return "EXECUTE"

        # Moderate confluence with good score
        if level == ConfluenceLevel.MODERATE:
            return "EXECUTE" if score >= 60 else "REDUCE_SIZE"

        # Weak confluence
        if level == ConfluenceLevel.WEAK:
            if score >= 50 and conflict_count == 0:
                return "REDUCE_SIZE"
            return "SKIP"

        # No confluence
        return "SKIP"


class ConfluenceBasedOrderFilter:
    """Order filter that uses confluence analysis to validate trades.

    This class integrates with OrderManager to check confluence before
    executing trades.

    Example:
        filter = ConfluenceBasedOrderFilter(analyzer)

        # Before executing order
        if filter.validate_trade(signal, position_size=100):
            execute_order()
        else:
            skip_or_reduce_size()
    """

    def __init__(
        self,
        analyzer: StrategyConfluenceAnalyzer,
        require_moderate_for_large_positions: bool = True,
        large_position_threshold: int = 50000,  # paisa
    ):
        """Initialize the filter.

        Args:
            analyzer: StrategyConfluenceAnalyzer instance
            require_moderate_for_large_positions: Require MODERATE+ for large positions
            large_position_threshold: Position size threshold in paisa
        """
        self.analyzer = analyzer
        self.require_moderate_for_large_positions = require_moderate_for_large_positions
        self.large_position_threshold = large_position_threshold

    def validate_trade(
        self,
        signal: StrategySignal,
        position_size: int,
    ) -> tuple[bool, float, str]:
        """Validate a trade using confluence analysis.

        Args:
            signal: The signal to validate
            position_size: Intended position size in paisa

        Returns:
            Tuple of (should_trade, size_multiplier, reason)
        """
        result = self.analyzer.get_confluence_for_signal(signal)

        # Check for conflicts
        if result.level == ConfluenceLevel.CONFLICT:
            return False, 0.0, f"Conflict detected: {result.conflicting_strategies}"

        # Check minimum confluence
        if result.level == ConfluenceLevel.NONE:
            return False, 0.0, "No confluence (single strategy)"

        # Large position check
        if self.require_moderate_for_large_positions:
            if position_size >= self.large_position_threshold:
                if result.level.value < ConfluenceLevel.MODERATE.value:
                    return (
                        False,
                        0.0,
                        f"Large position requires MODERATE+ confluence, got {result.level.name}"
                    )

        # Apply recommendations
        if result.recommendation == "EXECUTE":
            return True, 1.0, f"Strong confluence: {result.score:.1f}"
        elif result.recommendation == "REDUCE_SIZE":
            # Reduce size based on confluence level
            if result.level == ConfluenceLevel.WEAK:
                return True, 0.5, f"Weak confluence, reducing size 50%: {result.score:.1f}"
            else:
                return True, 0.75, f"Moderate confluence, reducing size 25%: {result.score:.1f}"
        else:
            return False, 0.0, f"Confluence too low: {result.level.name} ({result.score:.1f})"

    def get_position_size_multiplier(self, signal: StrategySignal) -> float:
        """Get position size multiplier based on confluence.

        Args:
            signal: The signal to analyze

        Returns:
            Multiplier for position size (0.0 to 1.0)
        """
        result = self.analyzer.get_confluence_for_signal(signal)

        if result.recommendation == "SKIP":
            return 0.0
        elif result.recommendation == "REDUCE_SIZE":
            return 0.5 if result.level == ConfluenceLevel.WEAK else 0.75
        else:
            # EXECUTE - can increase size for strong confluence
            if result.level == ConfluenceLevel.STRONG:
                return 1.25
            return 1.0
