"""Strategy engine for managing and executing trading strategies.

Provides the core infrastructure for running multiple strategies concurrently,
evaluating conditions on bar close, and generating trading signals.
"""

import queue
import threading
import time
from dataclasses import dataclass, field
from datetime import date, datetime, time as dt_time, timedelta
from pathlib import Path
from typing import Any, Optional
from zoneinfo import ZoneInfo

import pandas as pd
from loguru import logger

from src.strategy.builder import (
    EntrySet,
    SignalType,
    StrategyBuilder,
    StrategyConfig,
    TradingHours,
)
from src.strategy.conditions import (
    ADX_THRESHOLD_TRENDING,
    ConditionEvaluator,
    FilterResult,
    MultiTimeframeConfluence,
)

# Optional imports for research module integration
try:
    from src.research.multi_strategy import (
        StrategyConfluenceAnalyzer,
        ConfluenceLevel,
        StrategySignal,
    )
except ImportError:
    StrategyConfluenceAnalyzer = None  # type: ignore[misc,assignment]
    ConfluenceLevel = None  # type: ignore[misc,assignment]
    StrategySignal = None  # type: ignore[misc,assignment]

# Optional import for event calendar
try:
    from src.research.event_calendar import EventCalendarAnalyzer
except ImportError:
    EventCalendarAnalyzer = None  # type: ignore[misc,assignment]

IST = ZoneInfo("Asia/Kolkata")

# Market timing constants
MARKET_OPEN_TIME = dt_time(9, 15)
ORB_WINDOW_END = dt_time(9, 30)
MORNING_SESSION_END = dt_time(11, 30)
LUNCH_SESSION_START = dt_time(11, 30)
LUNCH_SESSION_END = dt_time(13, 30)
AFTERNOON_SESSION_START = dt_time(13, 30)
AFTERNOON_SESSION_END = dt_time(15, 0)  # Extended for Power Hour (Scheme 5)
SQUARE_OFF_START = dt_time(15, 0)
MARKET_CLOSE_TIME = dt_time(15, 15)

# Expiry day constants
NIFTY_EXPIRY_DAY = 3  # Thursday (0=Monday, 6=Sunday)
BANKNIFTY_EXPIRY_DAY = 2  # Wednesday (since Nov 2024)


@dataclass
class Signal:
    """Trading signal generated by a strategy.

    This is the single, canonical Signal class used across the entire
    trading pipeline: strategy engine -> signal queue -> order manager.

    Attributes:
        strategy_name: Name of the strategy that generated this signal.
        set_name: Name of the entry set that triggered.
        instrument_key: Instrument identifier (e.g. "NSE_EQ|RELIANCE").
        signal_type: Type of signal (BUY_CE, BUY_PE, BUY, SELL).
        quantity: Number of units to trade.
        price: Suggested entry/limit price in PAISA (None for MARKET orders).
        stop_loss: Stop loss price in PAISA.
        target: Target price in PAISA.
        order_type: Order type string (default "MARKET").
        product_type: Product type string (default "I" for intraday/MIS).
        timestamp: When the signal was generated.
        underlying: Underlying symbol (for options).
        timeframe: Bar timeframe that generated this signal.
        trigger_price: Trigger price in PAISA (for SL orders).
        signal_id: Unique identifier for this signal.
        metadata: Additional signal metadata.
    """

    strategy_name: str
    set_name: str
    instrument_key: str
    signal_type: SignalType
    quantity: int = 0
    price: Optional[int] = None
    stop_loss: Optional[int] = None
    target: Optional[int] = None
    order_type: str = "MARKET"
    product_type: str = "I"
    timestamp: datetime = field(default_factory=lambda: datetime.now(IST))
    underlying: Optional[str] = None
    timeframe: str = "5m"
    trigger_price: Optional[int] = None
    confidence: float = 0.8  # Default confidence for AgentPipeline fallback
    signal_id: str = field(default_factory=lambda: __import__("uuid").uuid4().hex[:16])
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        """Ensure timestamp is timezone-aware."""
        if self.timestamp.tzinfo is None:
            self.timestamp = self.timestamp.replace(tzinfo=IST)
        else:
            self.timestamp = self.timestamp.astimezone(IST)

    def to_dict(self) -> dict[str, Any]:
        """Convert signal to dictionary."""
        return {
            "strategy_name": self.strategy_name,
            "set_name": self.set_name,
            "instrument_key": self.instrument_key,
            "signal_type": self.signal_type.value,
            "quantity": self.quantity,
            "price": self.price,
            "stop_loss": self.stop_loss,
            "target": self.target,
            "order_type": self.order_type,
            "product_type": self.product_type,
            "timestamp": self.timestamp.isoformat(),
            "underlying": self.underlying,
            "timeframe": self.timeframe,
            "trigger_price": self.trigger_price,
            "confidence": self.confidence,
            "signal_id": self.signal_id,
            "metadata": self.metadata,
        }


class SetEvaluator(threading.Thread):
    """Evaluator thread for a single strategy set.

    Runs in its own thread, waits for bar close notifications,
    evaluates entry conditions, and generates signals.
    """

    def __init__(
        self,
        strategy_config: StrategyConfig,
        entry_set: EntrySet,
        signal_queue: queue.Queue,
        bar_close_event: threading.Event,
        bars_provider: callable,
        stop_event: threading.Event,
    ):
        """Initialize the set evaluator.

        Args:
            strategy_config: Parent strategy configuration.
            entry_set: The entry set to evaluate.
            signal_queue: Queue for generated signals.
            bar_close_event: Event signaled when a bar closes.
            bars_provider: Callable that returns current bars dict.
            stop_event: Event to signal thread shutdown.
        """
        super().__init__(name=f"{strategy_config.name}_{entry_set.name}", daemon=True)

        self._config = strategy_config
        self._entry_set = entry_set
        self._signal_queue = signal_queue
        self._bar_close_event = bar_close_event
        self._bars_provider = bars_provider
        self._stop_event = stop_event

        self._evaluator = ConditionEvaluator()
        self._last_signal_time: Optional[datetime] = None
        self._signals_generated_today: int = 0

        # Resolve EntrySet.signal (str) → SignalType enum once at init.
        # EntrySet.signal is a plain string like "CE", "PE", "BUY", "SELL",
        # "BUY_CE", "BUY_PE", "STRADDLE" — NOT the SignalType enum.
        # The engine previously accessed self._resolved_signal_type which
        # doesn't exist on EntrySet; this resolves it to the correct type.
        _SIGNAL_MAP: dict[str, SignalType] = {
            "BUY": SignalType.BUY,
            "SELL": SignalType.SELL,
            "CE": SignalType.BUY_CE,
            "BUY_CE": SignalType.BUY_CE,
            "PE": SignalType.BUY_PE,
            "BUY_PE": SignalType.BUY_PE,
            "STRADDLE": SignalType.SELL,  # STRADDLE → SELL (split into CE+PE by OrderManager)
        }
        self._resolved_signal_type: SignalType = _SIGNAL_MAP.get(
            str(entry_set.signal).upper(), SignalType.SELL
        )

        # Enhanced filter configuration
        self._strict_mode = strategy_config.params.get("strict_mode", False)
        self._use_enhanced_filters = strategy_config.params.get(
            "use_enhanced_filters", True
        )
        self._adx_min = strategy_config.params.get("adx_min", ADX_THRESHOLD_TRENDING)
        self._adx_max = strategy_config.params.get("adx_max", None)
        self._volume_multiplier = strategy_config.params.get(
            "volume_multiplier", 1.2
        )
        self._require_confluence = strategy_config.params.get(
            "require_confluence", True
        )
        self._min_timeframes_aligned = strategy_config.params.get(
            "min_timeframes_aligned", 2
        )

        # VIX regime filter configuration
        self._vix_filter_enabled = strategy_config.params.get("vix_filter", True)
        self._vix_symbol = strategy_config.params.get("vix_symbol", "NSE_INDEX|INDIA_VIX")
        self._vix_high_threshold = strategy_config.params.get("vix_high_threshold", 18.0)  # >18% = high vol
        self._vix_low_threshold = strategy_config.params.get("vix_low_threshold", 12.0)   # <12% = low vol
        # Strategy type classification from config (optional override)
        self._strategy_type = strategy_config.params.get("strategy_type", "auto")  # auto|trend|mean_reversion|breakout

        # Cached VIX value from the most recently fetched bars (avoids double provider call)
        self._cached_vix: Optional[float] = None

        # Multi-timeframe bars provider (optional)
        self._bars_by_timeframe_provider: Optional[callable] = None

        logger.info(
            f"Initialized SetEvaluator for {strategy_config.name}/{entry_set.name} "
            f"(enhanced_filters={self._use_enhanced_filters}, strict_mode={self._strict_mode}, "
            f"vix_filter={self._vix_filter_enabled})"
        )

    def run(self) -> None:
        """Main evaluation loop."""
        logger.info(f"Starting evaluator thread: {self.name}")

        while not self._stop_event.is_set():
            # Wait for bar close or stop signal
            signaled = self._bar_close_event.wait(timeout=1.0)

            if not signaled:
                # Timeout - check stop event and continue
                continue

            # Clear the event for next bar
            self._bar_close_event.clear()

            if self._stop_event.is_set():
                break

            # Check if we should evaluate
            if not self._should_evaluate():
                continue

            # Get current bars
            try:
                bars = self._bars_provider()
            except Exception as e:
                logger.error(f"Failed to get bars: {e}")
                continue

            if not bars:
                logger.debug("No bars available for evaluation")
                continue

            # Evaluate conditions for each symbol
            for symbol in self._get_symbols_to_evaluate():
                try:
                    if self._evaluate_for_symbol(symbol, bars):
                        break  # Only one signal per bar per set
                except Exception as e:
                    logger.error(f"Error evaluating {symbol}: {e}")

        logger.info(f"Evaluator thread stopped: {self.name}")

    def _should_evaluate(self) -> bool:
        """Check if evaluation should run now.

        Returns:
            True if within trading hours and strategy is active.
        """
        if not self._config.active:
            return False

        now = datetime.now(IST)

        # Check trading hours
        trading_hours = self._config.trading_hours

        # Check day
        if now.weekday() not in trading_hours.days:
            return False

        # Check time
        current_time = now.time()
        if current_time < trading_hours.start or current_time > trading_hours.end:
            return False

        # Check max trades per day
        if self._config.max_trades_per_day:
            if self._signals_generated_today >= self._config.max_trades_per_day:
                return False

        # Reset daily counter if new day
        if self._last_signal_time:
            if self._last_signal_time.date() != now.date():
                self._signals_generated_today = 0

        # VIX regime filter: read from cached value set by the last bars fetch
        # (_evaluate_for_symbol sets _cached_vix so we avoid a double provider call)
        if self._vix_filter_enabled:
            if not self._check_vix_regime(None):
                logger.debug(
                    f"[{self._config.name}] VIX regime blocked: "
                    f"strategy_type={self._strategy_type}, vix_high={self._vix_high_threshold}, "
                    f"vix_low={self._vix_low_threshold}"
                )
                return False

        return True

    def _is_trading_allowed_time(self, timestamp: datetime) -> bool:
        """Check if current time is in allowed trading window.

        Implements time-of-day filtering with the following rules:
        - Allowed: 9:30-11:30 AM (morning session)
        - Allowed: 13:30-14:45 PM (afternoon session)
        - Blocked: 9:15-9:30 (opening volatility)
        - Blocked: 11:30-13:30 (lunch session)
        - Blocked: 14:45-15:15 (square-off period)

        Args:
            timestamp: Current timestamp (should be IST-aware).

        Returns:
            True if trading is allowed at this time.
        """
        # Ensure timestamp is in IST
        if timestamp.tzinfo is None:
            timestamp = timestamp.replace(tzinfo=IST)
        else:
            timestamp = timestamp.astimezone(IST)

        current_time = timestamp.time()

        # Morning session: 9:30 - 11:30
        if ORB_WINDOW_END <= current_time < MORNING_SESSION_END:
            return True

        # Afternoon session: 13:30 - 14:45
        if AFTERNOON_SESSION_START <= current_time < AFTERNOON_SESSION_END:
            return True

        return False

    def _determine_strategy_type(self) -> str:
        """Classify strategy as trend_following, mean_reversion, breakout, or theta_positive.

        Uses heuristic analysis of strategy name, entry conditions, and parameters.
        Returns "auto" if unable to classify.
        """
        name_lower = self._config.name.lower()
        # Check explicit config override first
        if self._strategy_type != "auto":
            return self._strategy_type

        # Heuristic classification by name/conditions
        # Trend following: uses moving average crossovers, Supertrend, MACD with ADX confirmation
        trend_keywords = ["supertrend", "ema_cross", "macd", "trend", "momentum"]
        if any(kw in name_lower for kw in trend_keywords):
            return "trend_following"

        # Mean reversion: uses RSI oversold/overbought, Bollinger Bands, CPR
        mr_keywords = ["cpr", "rsi", "bollinger", "bb", "mean_reversion", "reversal"]
        if any(kw in name_lower for kw in mr_keywords):
            return "mean_reversion"

        # Breakout: uses previous day high/low, opening range, VWAP breakout
        breakout_keywords = ["orb", "pdh", "pdl", "breakout", "vwap_breakout"]
        if any(kw in name_lower for kw in breakout_keywords):
            return "breakout"

        # Theta-positive (option selling): straddle, condor, credit spread, iron condor
        theta_keywords = ["straddle", "condor", "credit_spread", "iron_condor", "theta"]
        if any(kw in name_lower for kw in theta_keywords):
            return "theta_positive"

        # Check entry set signal types for options selling (CE/PE with SELL side inferred)
        # If strategy sells options (STRADDLE or sells CE/PE), it's likely theta-positive
        for entry in self._config.entry_sets:
            if entry.signal in ("SELL_CE", "SELL_PE", "STRADDLE"):
                return "theta_positive"

        return "auto"

    def _get_vix_value(self, bars: dict[str, pd.DataFrame]) -> Optional[float]:
        """Extract current VIX value from the bars dictionary.

        Looks for the VIX symbol configured in `_vix_symbol`.
        Returns the latest close price as a percentage (e.g., 15.5 for 15.5%).

        Args:
            bars: Current bars dict from provider.

        Returns:
            VIX value as float (percentage) or None if unavailable.
        """
        vix_key = self._vix_symbol
        if vix_key not in bars:
            return None
        vix_df = bars[vix_key]
        if vix_df.empty or "close" not in vix_df.columns:
            return None
        # VIX data is typically stored in percentage points (e.g., 15.5)
        close_val = vix_df["close"].iloc[-1]
        if pd.isna(close_val):
            return None
        return float(close_val)

    def _check_vix_regime(self, bars: dict | None = None) -> bool:
        """Check if current VIX level allows trading for this strategy type.

        Uses pre-fetched `bars` dict when available (avoids calling bars_provider
        a second time per bar). Falls back to _cached_vix if bars is None.

        Applies regime gating rules:
        - VIX > high_threshold (18%): only theta_positive strategies allowed
        - VIX < low_threshold (12%): only mean_reversion and breakout allowed
        - Between thresholds: all strategies allowed

        Returns:
            True if trading is allowed under current VIX regime.
        """
        try:
            # Prefer freshly-fetched bars; fall back to cached value
            if bars is not None:
                vix = self._get_vix_value(bars)
                self._cached_vix = vix  # update cache
            else:
                vix = self._cached_vix

            if vix is None:
                logger.debug(f"[{self._config.name}] VIX data not available, skipping regime filter")
                return True  # Fail open — don't block if VIX unavailable

            strategy_type = self._determine_strategy_type()
            logger.debug(f"[{self._config.name}] VIX={vix:.1f}%, strategy_type={strategy_type}")

            # High volatility regime — block non-theta strategies
            if vix > self._vix_high_threshold:
                if strategy_type not in ("theta_positive", "auto"):
                    logger.info(
                        f"[{self._config.name}] BLOCKED: VIX {vix:.1f}% > {self._vix_high_threshold}%, "
                        f"strategy type '{strategy_type}' not allowed in high-vol regime"
                    )
                    return False
                return True

            # Low volatility regime — block trend-following strategies
            if vix < self._vix_low_threshold:
                if strategy_type == "trend_following":
                    logger.info(
                        f"[{self._config.name}] BLOCKED: VIX {vix:.1f}% < {self._vix_low_threshold}%, "
                        f"trend strategy not allowed in low-vol regime"
                    )
                    return False
                return True

            # Normal regime (12-18%): all strategies allowed
            return True

        except Exception as e:
            logger.warning(f"[{self._config.name}] VIX regime check failed: {e}")
            return True  # Fail open

    def _is_expiry_day(self, symbol: str, timestamp: datetime) -> bool:
        """Check if today is expiry day for the symbol.

        For Nifty: Thursday expiry (day 3)
        For Bank Nifty: Wednesday expiry (day 2, since Nov 2024)

        Args:
            symbol: Trading symbol or underlying (e.g., 'BANKNIFTY', 'NIFTY').
            timestamp: Current timestamp (should be IST-aware).

        Returns:
            True if today is expiry day for the symbol.
        """
        # Ensure timestamp is in IST
        if timestamp.tzinfo is None:
            timestamp = timestamp.replace(tzinfo=IST)
        else:
            timestamp = timestamp.astimezone(IST)

        today = timestamp.date()
        weekday = today.weekday()

        # Normalize symbol to uppercase for comparison
        symbol_upper = symbol.upper()

        # Check for Bank Nifty
        if "BANKNIFTY" in symbol_upper or "NIFTY BANK" in symbol_upper:
            return weekday == BANKNIFTY_EXPIRY_DAY

        # Check for Nifty (but not Bank Nifty)
        if "NIFTY" in symbol_upper:
            return weekday == NIFTY_EXPIRY_DAY

        # Default to Thursday expiry for other instruments
        return weekday == NIFTY_EXPIRY_DAY

    def _check_event_calendar(self, timestamp: datetime) -> tuple[bool, str]:
        """Check if any high-impact events are occurring today.

        Uses EventCalendarAnalyzer to check for:
        - RBI MPC meetings
        - US Fed meetings
        - Budget day
        - Monthly expiry (handled separately in _is_expiry_day)

        Args:
            timestamp: Current timestamp (should be IST-aware).

        Returns:
            Tuple of (allowed: bool, reason: str).
            allowed=True if no blocking events, False if should avoid trading.
        """
        # Ensure timestamp is in IST
        if timestamp.tzinfo is None:
            timestamp = timestamp.replace(tzinfo=IST)
        else:
            timestamp = timestamp.astimezone(IST)

        # Check if EventCalendarAnalyzer is available
        if EventCalendarAnalyzer is None:
            logger.debug("EventCalendarAnalyzer not available, skipping event check")
            return True, "Event calendar not available"

        try:
            analyzer = EventCalendarAnalyzer()
            today = timestamp.date()

            # Check for high-impact events
            if analyzer.is_budget_day(today):
                return False, "Budget Day - extreme volatility expected"

            if analyzer.is_rbi_policy_day(today):
                return False, "RBI MPC policy announcement day"

            if analyzer.is_fed_day(today):
                return False, "US Fed policy announcement day"

            return True, "No high-impact events"

        except Exception as e:
            logger.warning(f"Failed to check event calendar: {e}")
            return True, f"Event check failed: {e}"

    def _evaluate_entry_sets(
        self,
        symbol: str,
        bars: dict[str, pd.DataFrame],
        timestamp: datetime | None = None,
    ) -> bool:
        """Evaluate entry sets with all filters applied.

        This method wraps the standard condition evaluation with additional
        filters: time-of-day, expiry day, and event calendar.

        Args:
            symbol: Symbol to evaluate.
            bars: Current market data bars.
            timestamp: Optional timestamp for filter evaluation (defaults to now).

        Returns:
            True if signal was generated.
        """
        if timestamp is None:
            timestamp = datetime.now(IST)

        # Ensure timestamp is in IST
        if timestamp.tzinfo is None:
            timestamp = timestamp.replace(tzinfo=IST)
        else:
            timestamp = timestamp.astimezone(IST)

        # Get strategy parameters
        avoid_expiry_day = self._config.params.get("avoid_expiry_day", False)
        check_events = self._config.params.get("check_events", True)
        time_filter_enabled = self._config.params.get("time_filter_enabled", True)

        # 1. Time-of-day filter
        if time_filter_enabled:
            if not self._is_trading_allowed_time(timestamp):
                current_time = timestamp.time()
                logger.debug(
                    f"[{symbol}] Time-of-day filter blocked: {current_time} "
                    f"not in allowed trading window"
                )
                return False

        # 2. Expiry day filter
        if avoid_expiry_day:
            underlying = self._instr_sel_get("underlying") or symbol
            if self._is_expiry_day(underlying, timestamp):
                logger.info(
                    f"[{symbol}] Expiry day filter blocked: "
                    f"{underlying} expires today"
                )
                return False

        # 3. Event calendar filter
        if check_events:
            allowed, reason = self._check_event_calendar(timestamp)
            if not allowed:
                logger.info(f"[{symbol}] Event calendar filter blocked: {reason}")
                return False

        # All filters passed, proceed with standard evaluation
        return self._evaluate_for_symbol(symbol, bars)

    def _instr_sel_get(self, attr: str, default=None):
        """Safe accessor for instrument_selection (handles both Pydantic model and dict).

        Args:
            attr: Attribute/key name to look up.
            default: Value to return when attr is absent or instrument_selection is None.

        Returns:
            The attribute value, or default.
        """
        sel = self._config.instrument_selection
        if sel is None:
            return default
        if isinstance(sel, dict):
            return sel.get(attr, default)
        return getattr(sel, attr, default)

    def _get_symbols_to_evaluate(self) -> list[str]:
        """Get list of symbols to evaluate for this set.

        For options-type strategies, evaluation is performed on the underlying
        instrument (spot index). Order placement uses resolved option contracts
        separately (see instrument_resolver).
        """
        sel_type = self._instr_sel_get("type")
        if sel_type == "options":
            underlying = self._config.underlying or {}
            if isinstance(underlying, dict):
                ik = underlying.get("instrument_key")
            else:
                ik = getattr(underlying, "instrument_key", None)
            return [ik] if ik else []
        return self._instr_sel_get("symbols", []) or []

    def set_multi_timeframe_provider(self, provider: callable) -> None:
        """Set provider for multi-timeframe bars.

        Args:
            provider: Callable that returns dict mapping timeframe to bars dict.
        """
        self._bars_by_timeframe_provider = provider

    def _evaluate_for_symbol(
        self, symbol: str, bars: dict[str, pd.DataFrame]
    ) -> bool:
        """Evaluate conditions for a specific symbol.

        Args:
            symbol: Symbol to evaluate.
            bars: Current market data bars.

        Returns:
            True if signal was generated.
        """
        if symbol not in bars:
            return False

        # Update VIX cache from current bars (avoids double provider call in _should_evaluate)
        if self._vix_filter_enabled:
            self._check_vix_regime(bars)

        # Check if we have enough data
        symbol_bars = {symbol: bars[symbol]}
        if len(bars[symbol]) < 2:
            return False

        logger.info(
            "[{}|{}] Evaluating {} conditions | symbol={} | bars={}",
            self._config.name,
            self._entry_set.name,
            len(self._entry_set.conditions),
            symbol,
            len(bars[symbol]),
        )

        # Evaluate all conditions
        conditions_met = self._evaluator.evaluate_all(
            self._entry_set.conditions, symbol_bars, symbol
        )

        if not conditions_met:
            return False


        # Evaluate enhanced filters if enabled
        if self._use_enhanced_filters:
            signal_direction = self._get_signal_direction()

            # Get multi-timeframe bars if provider is set
            bars_by_timeframe = None
            if self._bars_by_timeframe_provider:
                try:
                    bars_by_timeframe = self._bars_by_timeframe_provider()
                except Exception as e:
                    logger.warning(f"Failed to get multi-timeframe bars: {e}")

            filters_passed, filter_results, confluence = (
                self._evaluator.evaluate_all_enhanced_filters(
                    bars=symbol_bars,
                    symbol=symbol,
                    signal_direction=signal_direction,
                    bars_by_timeframe=bars_by_timeframe,
                    strict_mode=self._strict_mode,
                    adx_min=self._adx_min,
                    adx_max=self._adx_max,
                    volume_multiplier=self._volume_multiplier,
                    require_confluence=self._require_confluence,
                    min_timeframes_aligned=self._min_timeframes_aligned,
                )
            )

            # Log filter results for debugging
            self._log_filter_results(symbol, filter_results, confluence)

            if not filters_passed:
                logger.debug(
                    f"Enhanced filters rejected signal for {symbol} "
                    f"(strict_mode={self._strict_mode})"
                )
                return False

            # Add filter metadata to signal
            filter_metadata = self._build_filter_metadata(filter_results, confluence)
        else:
            filter_metadata = {}

        # Generate signal
        signal = self._generate_signal(symbol, bars[symbol], filter_metadata)
        if signal:
            self._signal_queue.put(signal)
            self._last_signal_time = datetime.now(IST)
            self._signals_generated_today += 1
            logger.info(
                f"Generated signal: {signal.signal_type.value} {signal.instrument_key} "
                f"for strategy {self._config.name}"
            )
            return True

        return False

    def _get_signal_direction(self) -> str:
        """Get signal direction as 'long' or 'short'.

        Returns:
            'long' for BUY/BUY_CE, 'short' for SELL/BUY_PE.
        """
        if self._resolved_signal_type in (SignalType.BUY, SignalType.BUY_CE):
            return "long"
        return "short"

    def _log_filter_results(
        self,
        symbol: str,
        filter_results: list[FilterResult],
        confluence: MultiTimeframeConfluence | None,
    ) -> None:
        """Log enhanced filter results for debugging.

        Args:
            symbol: Symbol being evaluated.
            filter_results: List of filter results.
            confluence: Multi-timeframe confluence result (if applicable).
        """
        for result in filter_results:
            status = "PASS" if result.passed else "FAIL"
            logger.debug(
                f"[{symbol}] {result.filter_name}: {status} "
                f"(score: {result.score:.2f})"
            )
            # Log key details
            for key, value in result.details.items():
                if key not in ("error",):
                    logger.debug(f"  - {key}: {value}")

        if confluence:
            logger.debug(
                f"[{symbol}] Confluence: {confluence.aligned_count}/{confluence.total_count} "
                f"aligned (score: {confluence.alignment_score:.2f})"
            )

    def _build_filter_metadata(
        self,
        filter_results: list[FilterResult],
        confluence: MultiTimeframeConfluence | None,
    ) -> dict[str, Any]:
        """Build metadata dict from filter results for signal.

        Args:
            filter_results: List of filter results.
            confluence: Multi-timeframe confluence result.

        Returns:
            Metadata dict for signal.
        """
        metadata: dict[str, Any] = {
            "enhanced_filters_applied": True,
            "filter_results": {},
        }

        for result in filter_results:
            metadata["filter_results"][result.filter_name] = {
                "passed": result.passed,
                "score": result.score,
                "details": result.details,
            }

        if confluence:
            metadata["confluence"] = {
                "aligned_count": confluence.aligned_count,
                "total_count": confluence.total_count,
                "alignment_score": confluence.alignment_score,
                "timeframe_signals": confluence.timeframe_signals,
            }

        return metadata

    def _generate_signal(
        self,
        symbol: str,
        df: pd.DataFrame,
        filter_metadata: dict[str, Any] | None = None,
    ) -> Optional[Signal]:
        """Generate a signal for the given symbol.

        Args:
            symbol: Trading symbol.
            df: OHLCV DataFrame.
            filter_metadata: Optional metadata from enhanced filters.

        Returns:
            Signal object or None if generation failed.
        """
        try:
            # Get current price (close of latest bar)
            current_price = int(df["close"].iloc[-1])

            # Calculate SL and target first (needed for risk-based sizing)
            stop_loss = self._calculate_stop_loss(current_price, df, symbol)
            target = self._calculate_target(current_price, df, symbol)

            # Calculate quantity based on position sizing
            # Research score will be applied later by order manager
            quantity = self._calculate_quantity(
                current_price=current_price,
                stop_loss=stop_loss,
                df=df,
                research_score=None,  # Will be applied in order manager
                symbol=symbol,
            )

            # Get underlying for options
            underlying = None
            if self._resolved_signal_type in (SignalType.BUY_CE, SignalType.BUY_PE):
                underlying = self._instr_sel_get("underlying") or symbol

            # Build metadata
            metadata: dict[str, Any] = {
                "set_priority": self._entry_set.priority,
            }
            if filter_metadata:
                metadata.update(filter_metadata)

            # Pass instrument selection config to OrderManager for option resolution
            if hasattr(self._config, "instrument_selection") and self._config.instrument_selection:
                sel = self._config.instrument_selection
                metadata["instrument_selection"] = sel.model_dump() if hasattr(sel, "model_dump") else sel
            
            if hasattr(self._config, "underlying") and self._config.underlying:
                und = self._config.underlying
                metadata["underlying"] = und.model_dump() if hasattr(und, "model_dump") else und

            signal = Signal(
                strategy_name=self._config.name,
                set_name=self._entry_set.name,
                instrument_key=symbol,
                signal_type=self._resolved_signal_type,
                underlying=underlying,
                quantity=quantity,
                price=current_price,
                stop_loss=stop_loss,
                target=target,
                timestamp=datetime.now(IST),
                timeframe=self._config.timeframe,
                metadata=metadata,
            )

            return signal

        except Exception as e:
            logger.error(f"Failed to generate signal for {symbol}: {e}")
            return None

    def _calculate_quantity(
        self,
        current_price: int,
        stop_loss: int | None = None,
        df: pd.DataFrame | None = None,
        research_score: float | None = None,
        symbol: str | None = None,
    ) -> int:
        """Calculate position quantity based on sizing method.

        Implements multiple position sizing methods:
        - fixed_quantity: Fixed number of units
        - fixed_capital: Fixed capital per trade
        - percent_of_equity: Percentage of total equity
        - risk_based: Fixed fractional sizing based on risk per trade
        - kelly: Kelly Criterion sizing (conservative half-Kelly)

        Applies additional adjustments:
        - Research score scaling (score 75-100: 1.0x, 65-74: 0.7x, <65: 0x, >90: 1.25x)
        - Volatility adjustment (high ATR: -25%, low ATR: +10%)

        Args:
            current_price: Current price in PAISA.
            stop_loss: Stop loss price in PAISA (required for risk_based sizing).
            df: OHLCV DataFrame for ATR/volatility calculations.
            research_score: Optional research score (0-100) for size scaling.

        Returns:
            Quantity to trade (in units, respecting lot_size if applicable).
        """
        sizing = self._config.position_sizing
        quantity = 1

        # Get lot size for the instrument (default to 1 for equity)
        lot_size = self._get_lot_size()

        # Calculate base quantity based on sizing method
        if sizing.method.value == "fixed_quantity":
            quantity = sizing.quantity or 1

        elif sizing.method.value == "fixed_capital":
            capital = sizing.capital_per_trade or 100000  # Default 1000 INR in paisa
            qty = capital // current_price
            quantity = max(qty, sizing.min_quantity or 1)

        elif sizing.method.value == "percent_of_equity":
            # Get equity from risk manager if available, else use placeholder
            equity = self._get_account_equity()
            capital = equity * (sizing.percent_of_equity or 10.0) / 100
            qty = int(capital // current_price)
            quantity = max(qty, sizing.min_quantity or 1)

        elif sizing.method.value == "risk_based":
            # Fixed fractional sizing: Risk per trade / (Entry - SL)
            quantity = self._calculate_risk_based_quantity(
                current_price, stop_loss, sizing.risk_per_trade_percent or 1.0
            )

        elif sizing.method.value == "kelly":
            # Kelly Criterion sizing (conservative half-Kelly)
            quantity = self._calculate_kelly_quantity(current_price, df)

        # Apply research score scaling
        quantity = self._apply_research_score_scaling(quantity, research_score)

        # Apply volatility adjustment
        quantity = self._apply_volatility_adjustment(quantity, df, symbol)

        # Round to lot size
        quantity = self._round_to_lot_size(quantity, lot_size)

        # Apply max position size cap from risk manager config
        quantity = self._apply_position_size_cap(quantity, current_price)

        return max(quantity, sizing.min_quantity or 1)

    def _get_lot_size(self) -> int:
        """Get lot size for the instrument.

        Returns:
            Lot size (default 1 for equity, actual lot size for F&O).
        """
        # Try to get lot size from instrument manager if available
        # For now, default to 1 (equity) or check config
        symbols = self._instr_sel_get("symbols", []) or []
        if symbols:
            # F&O instruments typically have lot sizes > 1
            # This would be resolved from instrument master in production
            symbol = symbols[0]
            # Check if it's an F&O instrument by pattern (simplified)
            if any(x in symbol for x in ["FUT", "CE", "PE", "OPT"]):
                # Default lot sizes for major indices (would come from instrument master)
                if "NIFTY" in symbol and "BANKNIFTY" not in symbol:
                    return 75  # NIFTY lot size
                elif "BANKNIFTY" in symbol:
                    return 30  # BANKNIFTY lot size
                elif "FINNIFTY" in symbol:
                    return 65  # FINNIFTY lot size
                elif "SENSEX" in symbol:
                    return 20  # SENSEX lot size
        return 1  # Default for equity

    def _get_account_equity(self) -> int:
        """Get total account equity in paisa.

        Returns:
            Account equity in paisa (default 10L INR placeholder).
        """
        # In production, this would come from broker/risk manager
        # Default to 10,00,000 INR = 100,000,000 paisa
        return 100000000

    def _calculate_risk_based_quantity(
        self,
        entry_price: int,
        stop_loss: int | None,
        risk_per_trade_percent: float,
    ) -> int:
        """Calculate quantity using fixed fractional risk-based sizing.

        Formula: Position Size = Risk Amount / (Entry - SL) in points

        Args:
            entry_price: Entry price in PAISA.
            stop_loss: Stop loss price in PAISA.
            risk_per_trade_percent: Risk per trade as % of capital (e.g., 1.0 for 1%).

        Returns:
            Calculated quantity.
        """
        if stop_loss is None or stop_loss <= 0:
            # Fallback to fixed capital if no SL provided
            equity = self._get_account_equity()
            capital = equity * risk_per_trade_percent / 100
            return int(capital // entry_price)

        # Calculate risk amount in paisa
        equity = self._get_account_equity()
        risk_amount = int(equity * risk_per_trade_percent / 100)

        # Calculate risk per unit (stop loss distance in paisa)
        risk_per_unit = abs(entry_price - stop_loss)

        if risk_per_unit <= 0:
            # Avoid division by zero - fallback to fixed capital
            capital = equity * risk_per_trade_percent / 100
            return int(capital // entry_price)

        # Position size = Risk Amount / Risk per unit
        quantity = risk_amount // risk_per_unit

        return max(quantity, 1)

    def _calculate_kelly_quantity(
        self,
        current_price: int,
        df: pd.DataFrame | None,
    ) -> int:
        """Calculate quantity using Kelly Criterion (conservative half-Kelly).

        Kelly % = (Win Rate - (1 - Win Rate) / Avg Win:Loss Ratio)
        Position Size = Account * Kelly% * 0.5 (half-Kelly for safety)

        Args:
            current_price: Current price in PAISA.
            df: OHLCV DataFrame for calculating win rate from historical performance.

        Returns:
            Calculated quantity.
        """
        # Default Kelly parameters (would be calibrated from backtest data)
        # Conservative defaults for intraday trading
        win_rate = 0.45  # 45% win rate assumption
        avg_win_loss_ratio = 1.5  # Average win is 1.5x average loss

        # Try to extract better estimates from strategy metadata if available
        if hasattr(self._config, 'params') and self._config.params:
            win_rate = self._config.params.get('kelly_win_rate', win_rate)
            avg_win_loss_ratio = self._config.params.get('kelly_win_loss_ratio', avg_win_loss_ratio)

        # Calculate Kelly percentage
        # Kelly % = W - (1 - W) / R
        # Where W = win rate, R = avg win/loss ratio
        if avg_win_loss_ratio <= 0:
            avg_win_loss_ratio = 1.0  # Prevent division by zero

        kelly_pct = win_rate - ((1 - win_rate) / avg_win_loss_ratio)

        # Kelly can be negative (don't trade) - cap at 0
        kelly_pct = max(0.0, kelly_pct)

        # Apply half-Kelly for safety (conservative approach)
        half_kelly_pct = kelly_pct * 0.5

        # Cap at reasonable maximum (e.g., 10% of account per trade)
        half_kelly_pct = min(half_kelly_pct, 0.10)

        # Calculate position size
        equity = self._get_account_equity()
        capital_allocation = int(equity * half_kelly_pct)
        quantity = capital_allocation // current_price

        logger.debug(
            f"Kelly sizing: win_rate={win_rate:.2f}, W/L={avg_win_loss_ratio:.2f}, "
            f"kelly_pct={kelly_pct:.4f}, half_kelly_pct={half_kelly_pct:.4f}, "
            f"capital={capital_allocation}, qty={quantity}"
        )

        return max(quantity, 1)

    def _apply_research_score_scaling(self, quantity: int, research_score: float | None) -> int:
        """Apply research score-based position sizing multiplier.

        Score scaling:
        - Score 75-100: 1.0x size (full size)
        - Score 65-74: 0.7x size (REDUCE_SIZE)
        - Score < 65: 0x (SKIP - should not reach here)
        - Score > 90: 1.25x size (high conviction boost)

        Args:
            quantity: Base calculated quantity.
            research_score: Research score (0-100) or None.

        Returns:
            Adjusted quantity.
        """
        if research_score is None:
            return quantity

        multiplier = 1.0

        if research_score > 90:
            # High conviction - boost size
            multiplier = 1.25
        elif research_score >= 75:
            # Full size
            multiplier = 1.0
        elif research_score >= 65:
            # Reduced size
            multiplier = 0.7
        else:
            # Skip - return 0 (should be filtered earlier)
            multiplier = 0.0

        adjusted_qty = int(quantity * multiplier)

        logger.debug(
            f"Research score scaling: score={research_score:.1f}, "
            f"multiplier={multiplier}, qty={quantity} -> {adjusted_qty}"
        )

        return max(adjusted_qty, 0)

    def _apply_volatility_adjustment(self, quantity: int, df: pd.DataFrame | None, symbol: str) -> int:
        """Apply volatility-based position size adjustment using ATR.

        Uses cached IndicatorEngine from ConditionEvaluator when available to avoid
        O(N) recomputation per bar.

        Reduces position size during high volatility (ATR > 1.5× its 20-bar average)
        and increases slightly during low volatility (ATR < 0.75× average).

        Args:
            quantity: Current quantity.
            df: OHLCV DataFrame for ATR calculation.
            symbol: Trading symbol for engine cache lookup.

        Returns:
            Adjusted quantity.
        """
        if df is None or len(df) < 20:
            return quantity

        try:
            from src.strategy.indicators import IndicatorEngine

            # Try to reuse cached engine from ConditionEvaluator
            engine = None
            if hasattr(self, '_evaluator') and self._evaluator:
                engine = self._evaluator.get_engine(symbol)
                if engine:
                    # Incrementally update engine with latest data
                    engine.update(df)
            if engine is None:
                # Fallback: create fresh engine (cold start or missing cache)
                engine = IndicatorEngine(df)

            atr_series = engine.atr(14)

            if len(atr_series) < 20:
                return quantity

            current_atr = atr_series.iloc[-1]
            avg_atr = atr_series.iloc[-20:].mean()

            if avg_atr <= 0:
                return quantity

            atr_ratio = current_atr / avg_atr
            multiplier = 1.0

            if atr_ratio > 1.5:
                multiplier = 0.75
                logger.debug(f"High volatility adjustment: ATR ratio={atr_ratio:.2f}, reducing size by 25%")
            elif atr_ratio < 0.75:
                multiplier = 1.10
                logger.debug(f"Low volatility adjustment: ATR ratio={atr_ratio:.2f}, increasing size by 10%")

            adjusted_qty = int(quantity * multiplier)
            return max(adjusted_qty, 1)

        except Exception as e:
            logger.warning(f"Failed to apply volatility adjustment: {e}")
            return quantity

    def _round_to_lot_size(self, quantity: int, lot_size: int) -> int:
        """Round quantity down to nearest lot size multiple.

        Args:
            quantity: Raw quantity.
            lot_size: Lot size for the instrument.

        Returns:
            Quantity rounded to lot size.
        """
        if lot_size <= 1:
            return quantity
        return (quantity // lot_size) * lot_size

    def _apply_position_size_cap(self, quantity: int, current_price: int) -> int:
        """Apply maximum position size cap from risk configuration.

        Args:
            quantity: Current quantity.
            current_price: Current price in PAISA.

        Returns:
            Capped quantity.
        """
        sizing = self._config.position_sizing

        # Apply max_quantity cap if configured
        if sizing.max_quantity and quantity > sizing.max_quantity:
            logger.debug(f"Applying max_quantity cap: {quantity} -> {sizing.max_quantity}")
            return sizing.max_quantity

        # Apply max_position_size_pct cap from risk management
        max_position_size_pct = self._config.risk_management.get('max_position_size_pct', 20)
        equity = self._get_account_equity()
        max_position_value = equity * max_position_size_pct // 100
        max_qty_by_cap = max_position_value // current_price

        if quantity > max_qty_by_cap:
            logger.debug(f"Applying position size cap: {quantity} -> {max_qty_by_cap}")
            return max(max_qty_by_cap, 1)

        return quantity

    def _calculate_stop_loss(self, entry_price: int, df: pd.DataFrame, symbol: str) -> Optional[int]:
        """Calculate stop loss price.

        Uses cached IndicatorEngine when available.

        Args:
            entry_price: Entry price in PAISA.
            df: OHLCV DataFrame for ATR calculation.
            symbol: Trading symbol for engine cache lookup.

        Returns:
            Stop loss price in PAISA or None.
        """
        sl_rule = self._config.exit_rules.stop_loss_pct
        if sl_rule is None:
            return None

        if isinstance(sl_rule, (int, float)):
            points = int(sl_rule)
            if self._resolved_signal_type in (SignalType.BUY, SignalType.BUY_CE):
                return entry_price - points
            else:
                return entry_price + points

        elif isinstance(sl_rule, str) and "xatr" in sl_rule.lower():
            try:
                multiplier = float(sl_rule.lower().replace("xatr", ""))
                from src.strategy.indicators import IndicatorEngine

                engine = None
                if hasattr(self, '_evaluator') and self._evaluator:
                    engine = self._evaluator.get_engine(symbol)
                    if engine:
                        engine.update(df)
                if engine is None:
                    engine = IndicatorEngine(df)

                atr = engine.atr(14)
                atr_value = int(atr.iloc[-1])
                points = int(atr_value * multiplier)

                if self._resolved_signal_type in (SignalType.BUY, SignalType.BUY_CE):
                    return entry_price - points
                else:
                    return entry_price + points
            except Exception as e:
                logger.error(f"Failed to calculate ATR-based SL: {e}")
                return None

        return None

    def _calculate_target(self, entry_price: int, df: pd.DataFrame, symbol: str) -> Optional[int]:
        """Calculate target price.

        Uses cached IndicatorEngine when available.

        Args:
            entry_price: Entry price in PAISA.
            df: OHLCV DataFrame for ATR calculation.
            symbol: Trading symbol for engine cache lookup.

        Returns:
            Target price in PAISA or None.
        """
        target_rule = self._config.exit_rules.target_pct
        if target_rule is None:
            return None

        if isinstance(target_rule, (int, float)):
            points = int(target_rule)
            if self._resolved_signal_type in (SignalType.BUY, SignalType.BUY_CE):
                return entry_price + points
            else:
                return entry_price - points

        elif isinstance(target_rule, str) and "xatr" in target_rule.lower():
            try:
                multiplier = float(target_rule.lower().replace("xatr", ""))
                from src.strategy.indicators import IndicatorEngine

                engine = None
                if hasattr(self, '_evaluator') and self._evaluator:
                    engine = self._evaluator.get_engine(symbol)
                    if engine:
                        engine.update(df)
                if engine is None:
                    engine = IndicatorEngine(df)

                atr = engine.atr(14)
                atr_value = int(atr.iloc[-1])
                points = int(atr_value * multiplier)

                if self._resolved_signal_type in (SignalType.BUY, SignalType.BUY_CE):
                    return entry_price + points
                else:
                    return entry_price - points
            except Exception as e:
                logger.error(f"Failed to calculate ATR-based target: {e}")
                return None

        return None


class StrategyEngine:
    """Main strategy engine that manages multiple strategies.

    Loads strategies from a directory, creates evaluator threads for each,
    and manages the signal queue.
    """

    def __init__(
        self,
        strategies_dir: str | Path,
        bars_provider: callable,
        check_interval: float = 1.0,
        enable_confluence: bool = True,
        min_confluence_level: str = "WEAK",
    ):
        """Initialize the strategy engine.

        Args:
            strategies_dir: Directory containing strategy YAML/JSON files.
            bars_provider: Callable that returns dict of symbol -> DataFrame.
            check_interval: How often to check for bar close (seconds).
            enable_confluence: Whether to enable multi-strategy confluence analysis.
            min_confluence_level: Minimum confluence level required (NONE, WEAK, MODERATE, STRONG).
        """
        self._strategies_dir = Path(strategies_dir)
        self._bars_provider = bars_provider
        self._check_interval = check_interval

        self._strategies: dict[str, StrategyConfig] = {}
        self._evaluators: list[SetEvaluator] = []
        self._signal_queue: queue.Queue[Signal] = queue.Queue()
        self._bar_close_event = threading.Event()
        self._stop_event = threading.Event()
        # Initialized in start(); guarded in stop() against pre-start shutdown.
        self._monitor_thread: threading.Thread | None = None

        self._builder = StrategyBuilder()
        self._evaluator = ConditionEvaluator()  # shared evaluator for sync path
        # Per-strategy evaluators reused across bars in evaluate_bar_sync.
        # Each strategy has a fixed timeframe, so its IndicatorEngine cache
        # stays consistent — avoids the O(N) per-bar rebuild.
        self._sync_evaluators: dict[str, ConditionEvaluator] = {}
        self._last_bar_times: dict[str, datetime] = {}

        # Backtest signal cooldown: strategy_name -> last signal bar_time
        # Prevents generating duplicate signals on consecutive bars
        self._backtest_last_signal: dict[str, datetime] = {}
        self._backtest_signal_count: dict[str, int] = {}  # strategy -> signals today

        # Initialize confluence analyzer if available
        self._confluence_analyzer: Optional[StrategyConfluenceAnalyzer] = None
        if enable_confluence and StrategyConfluenceAnalyzer is not None:
            try:
                # Parse confluence level
                level_map = {
                    "NONE": ConfluenceLevel.NONE,
                    "WEAK": ConfluenceLevel.WEAK,
                    "MODERATE": ConfluenceLevel.MODERATE,
                    "STRONG": ConfluenceLevel.STRONG,
                }
                min_level = level_map.get(min_confluence_level.upper(), ConfluenceLevel.WEAK)

                self._confluence_analyzer = StrategyConfluenceAnalyzer(
                    min_confluence_level=min_level
                )
                logger.info(f"StrategyConfluenceAnalyzer initialized (min_level={min_confluence_level})")
            except Exception as e:
                logger.warning(f"Failed to initialize confluence analyzer: {e}")
                self._confluence_analyzer = None

        logger.info(f"StrategyEngine initialized with dir: {strategies_dir}")

    def load_strategies(self) -> int:
        """Load all strategies from the strategies directory.

        Returns:
            Number of strategies loaded.
        """
        if not self._strategies_dir.exists():
            logger.warning(f"Strategies directory not found: {self._strategies_dir}")
            return 0

        configs = self._builder.load_strategies_from_directory(self._strategies_dir)

        for config in configs:
            if config.active:
                self._strategies[config.name] = config
                self._register_strategy_with_confluence(config)
                logger.info(f"Loaded active strategy: {config.name}")
            else:
                logger.info(f"Loaded inactive strategy: {config.name}")

        return len(self._strategies)

    def add_strategy(self, config: StrategyConfig) -> None:
        """Add a strategy programmatically.

        Args:
            config: Strategy configuration to add.
        """
        self._strategies[config.name] = config
        self._register_strategy_with_confluence(config)
        logger.info(f"Added strategy: {config.name}")

    # ------------------------------------------------------------------
    # Synchronous evaluation (backtest harness path)
    # ------------------------------------------------------------------

    _SIGNAL_MAP: dict[str, "SignalType"] = {
        "BUY": SignalType.BUY,
        "SELL": SignalType.SELL,
        "CE": SignalType.BUY_CE,
        "BUY_CE": SignalType.BUY_CE,
        "PE": SignalType.BUY_PE,
        "BUY_PE": SignalType.BUY_PE,
        "STRADDLE": SignalType.STRADDLE,
    }

    @staticmethod
    def _classify_strategy_type(strategy: StrategyConfig) -> str:
        """Classify strategy as trend_following, mean_reversion, breakout, or theta_positive.

        Uses heuristic analysis of strategy name and entry conditions.

        Args:
            strategy: StrategyConfig to classify.

        Returns:
            Strategy type string.
        """
        name_lower = strategy.name.lower()

        # Explicit override
        strat_type = strategy.params.get("strategy_type", "auto")
        if strat_type != "auto":
            return strat_type

        # Trend following: MA crossovers, Supertrend, MACD with ADX
        trend_kw = ["supertrend", "ema_cross", "macd", "trend", "momentum", "adx"]
        if any(kw in name_lower for kw in trend_kw):
            return "trend_following"

        # Mean reversion: RSI, Bollinger Bands, CPR
        mr_kw = ["cpr", "rsi", "bollinger", "bb", "mean_reversion", "reversal", "oscillator"]
        if any(kw in name_lower for kw in mr_kw):
            return "mean_reversion"

        # Breakout: PDH/PDL, ORB, VWAP breakout
        bo_kw = ["orb", "pdh", "pdl", "breakout", "vwap_breakout"]
        if any(kw in name_lower for kw in bo_kw):
            return "breakout"

        # Theta-positive: option selling strategies
        theta_kw = ["straddle", "condor", "credit_spread", "iron_condor", "theta", "short_option"]
        if any(kw in name_lower for kw in theta_kw):
            return "theta_positive"

        # Check entry signal types
        for entry in strategy.entry_sets:
            sig = entry.signal.upper()
            if sig in ("SELL_CE", "SELL_PE", "STRADDLE"):
                return "theta_positive"

        return "auto"

    def evaluate_bar_sync(
        self,
        bars: dict[str, pd.DataFrame],
        bar_time: datetime,
    ) -> list["Signal"]:
        """Evaluate all loaded strategies for one bar (no threads).

        Applies the same session-time filter and condition evaluation as the
        live SetEvaluator threads, but synchronously. Used by the backtest
        harness so that bar-by-bar results are deterministic.

        Args:
            bars: Mapping instrument_key -> OHLCV DataFrame (bars up to current).
            bar_time: Timestamp of the bar being evaluated (must be IST-aware).

        Returns:
            List of Signal objects generated this bar (may be empty).
        """
        if bar_time.tzinfo is None:
            bar_time = bar_time.replace(tzinfo=IST)
        else:
            bar_time = bar_time.astimezone(IST)

        current_time = bar_time.time()
        weekday = bar_time.weekday()
        signals: list[Signal] = []

        for strategy in self._strategies.values():
            if not strategy.enabled:
                continue

            # Trading hours filter (mirrors SetEvaluator._should_evaluate)
            th = strategy.trading_hours
            if weekday not in th.days:
                continue
            if not (th.start <= current_time <= th.end):
                continue

            # Signal cooldown — respect max_trades_per_day from strategy config
            max_trades = 3  # default
            if strategy.risk_management and isinstance(strategy.risk_management, dict):
                max_trades = strategy.risk_management.get("max_trades_per_day", 3)

            # Reset daily counter on new day
            last_sig = self._backtest_last_signal.get(strategy.name)
            if last_sig and last_sig.date() != bar_time.date():
                self._backtest_signal_count[strategy.name] = 0

            if self._backtest_signal_count.get(strategy.name, 0) >= max_trades:
                continue

            # Cooldown: skip if we already signaled within the strategy's timeframe period
            if last_sig:
                try:
                    tf_mins = int(strategy.timeframe.lower().replace("min", "").replace("m", ""))
                except (ValueError, AttributeError):
                    tf_mins = 5
                cooldown_bars = max(tf_mins, 5)  # at least 5 minutes between signals
                elapsed_mins = (bar_time - last_sig).total_seconds() / 60
                if elapsed_mins < cooldown_bars:
                    continue

            # VIX regime filter for backtest (mirrors SetEvaluator._check_vix_regime)
            if strategy.params.get("vix_filter", True):
                # Determine VIX value from bars
                vix_symbol = strategy.params.get("vix_symbol", "NSE_INDEX|INDIA_VIX")
                vix_value = None
                if vix_symbol in bars:
                    vix_df = bars[vix_symbol]
                    if not vix_df.empty and "close" in vix_df.columns:
                        vix_val = vix_df["close"].iloc[-1]
                        if pd.notna(vix_val):
                            vix_value = float(vix_val)
                if vix_value is not None:
                    # Determine strategy type (auto-detect or explicit)
                    strat_type = strategy.params.get("strategy_type", "auto")
                    if strat_type == "auto":
                        strat_type = self._classify_strategy_type(strategy)
                        
                    # Strict gating based on strategy params (applies to ALL strategies, including theta_positive)
                    max_vix = strategy.params.get("max_vix")
                    min_vix = strategy.params.get("min_vix")
                    
                    if max_vix is not None and vix_value > max_vix:
                        logger.debug(
                            f"[{strategy.name}] VIX {vix_value:.1f} > max_vix {max_vix}, strategy blocked"
                        )
                        continue
                        
                    if min_vix is not None and vix_value < min_vix:
                        logger.debug(
                            f"[{strategy.name}] VIX {vix_value:.1f} < min_vix {min_vix}, strategy blocked"
                        )
                        continue

                    # Heuristic/regime gating for trend strategies
                    vix_high = strategy.params.get("vix_high_threshold", 18.0)
                    vix_low = strategy.params.get("vix_low_threshold", 12.0)
                    if vix_value > vix_high and strat_type not in ("theta_positive", "auto"):
                        logger.debug(
                            f"[{strategy.name}] VIX {vix_value:.1f} > {vix_high}, "
                            f"strategy '{strat_type}' blocked in high-vol regime"
                        )
                        continue
                    if vix_value < vix_low and strat_type == "trend_following":
                        logger.debug(
                            f"[{strategy.name}] VIX {vix_value:.1f} < {vix_low}, "
                            f"trend strategy blocked in low-vol regime"
                        )
                        continue

            # Instrument key
            instrument_key: Optional[str] = None
            if strategy.underlying and isinstance(strategy.underlying, dict):
                instrument_key = strategy.underlying.get("instrument_key")
            if not instrument_key or instrument_key not in bars:
                continue

            if len(bars[instrument_key]) < 2:
                continue

            # Resample 1-min bars to the strategy's primary timeframe so
            # crossover/indicator checks operate on the correct candle resolution
            raw_df = bars[instrument_key]
            tf_str = strategy.timeframe  # e.g. "5min", "15min"
            try:
                tf_minutes = int(tf_str.lower().replace("min", "").replace("m", ""))
            except (ValueError, AttributeError):
                tf_minutes = 5
            if tf_minutes > 1:
                _agg = {"open": "first", "high": "max", "low": "min",
                        "close": "last", "volume": "sum"}
                resampled = raw_df.resample(f"{tf_minutes}min").agg(_agg).dropna()
                window = {instrument_key: resampled if len(resampled) >= 2 else raw_df}
            else:
                window = {instrument_key: raw_df}

            if len(window[instrument_key]) < 2:
                continue

            # Reuse a per-strategy evaluator so its IndicatorEngine cache
            # persists across bars. Safe because each strategy has a fixed
            # timeframe (the resampled `window` shape is stable per strategy).
            evaluator = self._sync_evaluators.get(strategy.name)
            if evaluator is None:
                evaluator = ConditionEvaluator()
                self._sync_evaluators[strategy.name] = evaluator

            # Evaluate each entry set
            for entry_set in strategy.entry_sets:
                try:
                    all_met = evaluator.evaluate_all(
                        entry_set.conditions, window, instrument_key
                    )
                except Exception as exc:
                    logger.debug(
                        f"[{strategy.name}/{entry_set.name}] Condition error: {exc}"
                    )
                    all_met = False

                if not all_met:
                    continue

                # Map signal string to SignalType
                signal_str = entry_set.signal.upper()
                signal_type = self._SIGNAL_MAP.get(signal_str, SignalType.BUY)
                is_buy = signal_str in ("BUY", "BUY_CE")

                # Quantity from position sizing
                quantity = 1
                if strategy.position_sizing and strategy.position_sizing.quantity:
                    quantity = strategy.position_sizing.quantity

                # Current price for SL/target calculation
                current_price = int(window[instrument_key]["close"].iloc[-1])

                # Calculate SL and target from strategy exit_rules
                stop_loss = None
                if strategy.exit_rules.stop_loss_pct is not None:
                    sl_pct = strategy.exit_rules.stop_loss_pct / 100
                    if is_buy:
                        stop_loss = int(current_price * (1 - sl_pct))
                    else:
                        stop_loss = int(current_price * (1 + sl_pct))

                target = None
                if strategy.exit_rules.target_pct is not None:
                    tgt_pct = strategy.exit_rules.target_pct / 100
                    if is_buy:
                        target = int(current_price * (1 + tgt_pct))
                    else:
                        target = int(current_price * (1 - tgt_pct))

                signal = Signal(
                    strategy_name=strategy.name,
                    set_name=entry_set.name,
                    instrument_key=instrument_key,
                    signal_type=signal_type,
                    quantity=quantity,
                    price=None,        # MARKET order — harness sets via update_ltp
                    stop_loss=stop_loss,
                    target=target,
                    order_type="MARKET",
                    product_type="I",  # intraday MIS
                    timestamp=bar_time,
                    timeframe=strategy.timeframe,
                    underlying=(
                        strategy.underlying.get("symbol")
                        if strategy.underlying else None
                    ),
                    metadata={
                        "stop_loss_pct": strategy.exit_rules.stop_loss_pct,
                        "target_pct": strategy.exit_rules.target_pct,
                        "source": "backtest",
                    },
                )
                signals.append(signal)
                # Record signal for cooldown tracking
                self._backtest_last_signal[strategy.name] = bar_time
                self._backtest_signal_count[strategy.name] = (
                    self._backtest_signal_count.get(strategy.name, 0) + 1
                )
                logger.debug(
                    f"[BACKTEST] Signal: {signal_type.value} "
                    f"{instrument_key} from {strategy.name}/{entry_set.name}"
                )
                break  # One signal per strategy per evaluation

        return signals

    def _register_strategy_with_confluence(self, config: StrategyConfig) -> None:
        """Register a strategy with the confluence analyzer.

        Args:
            config: Strategy configuration to register.
        """
        if self._confluence_analyzer is not None:
            try:
                # Get performance score from config params if available
                performance_score = config.params.get("performance_score", 1.0)
                win_rate = config.params.get("win_rate", 0.5)
                profit_factor = config.params.get("profit_factor", 1.0)

                self._confluence_analyzer.register_strategy(
                    name=config.name,
                    performance_score=performance_score,
                    win_rate=win_rate,
                    profit_factor=profit_factor,
                )
                logger.debug(f"Registered strategy with confluence analyzer: {config.name}")
            except Exception as e:
                logger.warning(f"Failed to register strategy with confluence analyzer: {e}")

    def start(self) -> None:
        """Start the strategy engine and all evaluator threads."""
        logger.info("Starting StrategyEngine...")

        # Create evaluator threads for each entry set
        for strategy in self._strategies.values():
            for entry_set in strategy.entry_sets:
                evaluator = SetEvaluator(
                    strategy_config=strategy,
                    entry_set=entry_set,
                    signal_queue=self._signal_queue,
                    bar_close_event=self._bar_close_event,
                    bars_provider=self._bars_provider,
                    stop_event=self._stop_event,
                )
                self._evaluators.append(evaluator)
                evaluator.start()

        logger.info(f"Started {len(self._evaluators)} evaluator threads")

        # Start the bar close monitor thread
        self._monitor_thread = threading.Thread(
            target=self._monitor_bar_close, daemon=True, name="BarCloseMonitor"
        )
        self._monitor_thread.start()

    def stop(self) -> None:
        """Stop the strategy engine and all evaluator threads."""
        logger.info("Stopping StrategyEngine...")
        self._stop_event.set()
        self._bar_close_event.set()  # Wake up any waiting threads

        # Wait for all evaluators to finish
        for evaluator in self._evaluators:
            evaluator.join(timeout=5.0)

        if self._monitor_thread is not None:
            self._monitor_thread.join(timeout=5.0)
        logger.info("StrategyEngine stopped")

    def _monitor_bar_close(self) -> None:
        """Monitor bars and signal bar close events."""
        logger.info("Bar close monitor started")

        while not self._stop_event.is_set():
            try:
                bars = self._bars_provider()
                if bars and self._check_bar_close(bars):
                    self._bar_close_event.set()
            except Exception as e:
                logger.error(f"Error monitoring bars: {e}")

            time.sleep(self._check_interval)

        logger.info("Bar close monitor stopped")

    def _check_bar_close(self, bars: dict[str, pd.DataFrame]) -> bool:
        """Check if any bar has closed (new bar started).

        Args:
            bars: Current bars dict.

        Returns:
            True if a new bar has started (previous bar closed).
        """
        new_close = False

        for symbol, df in bars.items():
            if len(df) == 0:
                continue

            last_time = df.index[-1]

            if isinstance(last_time, pd.Timestamp):
                if last_time.tzinfo is None:
                    last_time = last_time.replace(tzinfo=IST)
                else:
                    last_time = last_time.astimezone(IST)

            if symbol in self._last_bar_times:
                if last_time > self._last_bar_times[symbol]:
                    # New bar started, previous bar closed
                    new_close = True
                    logger.debug(f"Bar closed for {symbol} at {last_time}")

            self._last_bar_times[symbol] = last_time

        return new_close

    def get_signal(self, timeout: Optional[float] = None) -> Optional[Signal]:
        """Get the next signal from the queue.

        Args:
            timeout: Maximum time to wait for a signal.

        Returns:
            Signal object or None if timeout.
        """
        try:
            signal = self._signal_queue.get(timeout=timeout)
            # Track signal with confluence analyzer
            if signal is not None:
                self.track_signal_for_confluence(signal)
            return signal
        except queue.Empty:
            return None

    def get_all_signals(self) -> list[Signal]:
        """Get all pending signals from the queue.

        Returns:
            List of Signal objects.
        """
        signals = []
        while not self._signal_queue.empty():
            try:
                signal = self._signal_queue.get_nowait()
                if signal is not None:
                    signals.append(signal)
                    # Track signal with confluence analyzer
                    self.track_signal_for_confluence(signal)
            except queue.Empty:
                break
        return signals

    @property
    def strategies(self) -> list[StrategyConfig]:
        """Return all loaded strategies (active and inactive)."""
        return list(self._strategies.values())

    def get_active_strategies(self) -> list[StrategyConfig]:
        """Get list of currently active strategies.

        Returns:
            List of active StrategyConfig objects.
        """
        return [s for s in self._strategies.values() if s.active]

    def deactivate_strategy(self, name: str) -> bool:
        """Deactivate a strategy.

        Args:
            name: Strategy name.

        Returns:
            True if strategy was found and deactivated.
        """
        if name in self._strategies:
            self._strategies[name].active = False
            logger.info(f"Deactivated strategy: {name}")
            return True
        return False

    def activate_strategy(self, name: str) -> bool:
        """Activate a strategy.

        Args:
            name: Strategy name.

        Returns:
            True if strategy was found and activated.
        """
        if name in self._strategies:
            self._strategies[name].active = True
            logger.info(f"Activated strategy: {name}")
            return True
        return False

    def track_signal_for_confluence(self, signal: Signal) -> None:
        """Track a generated signal with the confluence analyzer.

        Args:
            signal: The signal to track.
        """
        if self._confluence_analyzer is not None and StrategySignal is not None:
            try:
                strategy_signal = StrategySignal(
                    strategy_name=signal.strategy_name,
                    signal_type=signal.signal_type.value,
                    confidence=70.0,  # Default confidence, could be enhanced
                    timestamp=signal.timestamp,
                    underlying=signal.underlying or signal.instrument_key,
                    entry_price=signal.price,
                    stop_loss=signal.stop_loss,
                    target=signal.target,
                )
                self._confluence_analyzer.add_signal(strategy_signal)
                logger.debug(
                    f"Tracked signal for confluence: {signal.strategy_name} -> "
                    f"{signal.signal_type.value} ({signal.instrument_key})"
                )
            except Exception as e:
                logger.warning(f"Failed to track signal for confluence: {e}")

    def get_confluence_analyzer(self) -> Optional[StrategyConfluenceAnalyzer]:
        """Get the confluence analyzer instance.

        Returns:
            StrategyConfluenceAnalyzer instance or None if not enabled.
        """
        return self._confluence_analyzer

    # ------------------------------------------------------------------
    # Wave-5 gate layer — set from TradingBot after modules are initialised
    # ------------------------------------------------------------------

    def set_wave5_modules(
        self,
        confluence_engine: Any = None,
        rejection_filter: Any = None,
        regime_router: Any = None,
        kelly_sizer: Any = None,
        kronos_forecaster: Any = None,
        db_engine: Any = None,
    ) -> None:
        """Inject Wave-5 gate modules into the engine.

        Called by TradingBot after _init_phase_modules().  When all three
        modules are set the engine can call _apply_wave5_gates() before
        forwarding signals.

        NOTE: The live SetEvaluator threads are NOT wired to these gates yet —
        they run on their own queues.  Gates are available for the synchronous
        evaluate_bar_sync() path and for external callers.  Full integration
        into the live emit path is deferred to the next session (see
        BLOOMBERG_BUILD_HANDOFF.md — CHANGE_LOG "wave5_emit_wiring: DEFERRED").

        Args:
            confluence_engine: ConfluenceEngine instance or None.
            rejection_filter: RejectionFilter instance or None.
            regime_router: RegimeRouter instance or None.
            kelly_sizer: KellySizer instance or None (reserved for future use).
            kronos_forecaster: KronosForecaster instance or None (Phase G shadow mode).
            db_engine: SQLAlchemy sync engine for Kronos forecast DB queries.
        """
        self._wave5_confluence = confluence_engine
        self._wave5_rejection = rejection_filter
        self._wave5_regime = regime_router
        self._kronos_forecaster = kronos_forecaster
        self._db_engine = db_engine
        gates_ok = sum(
            x is not None for x in (confluence_engine, rejection_filter, regime_router)
        )
        logger.info("Wave-5 gates injected into StrategyEngine: %d/3 modules available", gates_ok)
        if kronos_forecaster is not None:
            logger.info("Kronos shadow forecaster wired into StrategyEngine (MODEL_FORECAST dim)")

    def _build_kronos_dimension(self, signal: "Signal") -> Any:
        """Fetch latest Kronos forecast for signal's instrument and build a DimensionResult.

        Queries the ``kronos_forecasts`` table for the most recent forecast
        (within the last 10 minutes) for ``signal.instrument_key``.  Returns
        a MODEL_FORECAST DimensionResult, or None when unavailable.

        Shadow mode — result fed into ConfluenceEngine at weight 0.055 but
        does NOT directly alter trade decisions (dimension is included, but
        the engine's existing threshold logic applies as before).

        Args:
            signal: Candidate Signal object.

        Returns:
            DimensionResult for MODEL_FORECAST dimension, or None.
        """
        if not getattr(self, "_kronos_forecaster", None):
            return None
        if not getattr(self, "_db_engine", None):
            return None
        try:
            from sqlalchemy import text
            from src.strategy.kronos_dimension import kronos_dimension_result

            sql = text("""
                SELECT predicted_direction, predicted_change_pct, predicted_range_pct,
                       predicted_close_paisa, current_close_paisa, horizon_bars
                FROM kronos_forecasts
                WHERE instrument_key = :ikey
                  AND ts > NOW() - INTERVAL '10 minutes'
                ORDER BY ts DESC LIMIT 1
            """)
            with self._db_engine.connect() as conn:
                row = conn.execute(sql, {"ikey": signal.instrument_key}).fetchone()

            signal_type_str = (
                signal.signal_type.value
                if hasattr(signal.signal_type, "value")
                else str(signal.signal_type)
            )

            if row is None:
                return kronos_dimension_result(signal_type_str, None)

            forecast_summary = {
                "predicted_direction": row[0],
                "predicted_change_pct": float(row[1]) if row[1] is not None else 0.0,
                "predicted_range_pct": float(row[2]) if row[2] is not None else 0.0,
            }
            return kronos_dimension_result(
                signal_type=signal_type_str,
                forecast_summary=forecast_summary,
            )
        except Exception as exc:
            logger.warning("kronos dimension fetch failed: {}", exc)
            return None

    def _apply_wave5_gates(
        self,
        signal: "Signal",
        dimension_results: list[Any] | None = None,
        spread_bps: float = 0.0,
        open_positions: list[Any] | None = None,
    ) -> bool:
        """Pass a candidate signal through Wave-5 gates.

        Returns True if the signal should proceed to order placement,
        False if it should be rejected.

        This method is SAFE to call — all exceptions are caught and the
        signal is allowed through (graceful degrade) so that a gate
        failure never prevents legitimate trades.

        Args:
            signal: Candidate Signal object.
            dimension_results: Optional list of DimensionResult for confluence scoring.
            spread_bps: Current bid-ask spread in basis points.
            open_positions: List of currently open positions.
        """
        today = datetime.now(IST).date()

        # 0. Kronos MODEL_FORECAST dimension (shadow mode — appended to dimension_results)
        if dimension_results is None:
            dimension_results = []
        kronos_dim = self._build_kronos_dimension(signal)
        if kronos_dim is not None:
            dimension_results = list(dimension_results) + [kronos_dim]

        # 1. Regime router — is this strategy_type allowed today?
        regime_ok = True
        if hasattr(self, "_wave5_regime") and self._wave5_regime is not None:
            try:
                strategy_type = self._strategies.get(signal.strategy_name, None)
                if strategy_type is not None:
                    stype = StrategyEngine._classify_strategy_type(strategy_type)
                else:
                    stype = "auto"
                if not self._wave5_regime.is_strategy_type_allowed(stype, today):
                    reason = self._wave5_regime.get_blocked_reason(stype, today)
                    logger.info("Wave-5 regime gate blocked %s: %s", signal.strategy_name, reason)
                    regime_ok = False
            except Exception as exc:
                logger.debug("Wave-5 regime gate error (allow): {}", exc)

        if not regime_ok:
            return False

        # 2. Confluence score
        confluence_ok = True
        if hasattr(self, "_wave5_confluence") and self._wave5_confluence is not None and dimension_results:
            try:
                result = self._wave5_confluence.evaluate(
                    strategy_name=signal.strategy_name,
                    instrument_key=signal.instrument_key,
                    signal_type=signal.signal_type.value,
                    dimension_results=dimension_results,
                )
                if not result.get("passed", True):
                    logger.info(
                        "Wave-5 confluence gate blocked %s: score=%.1f < threshold=%.1f",
                        signal.strategy_name,
                        result.get("composite_score", 0),
                        result.get("threshold", 70),
                    )
                    confluence_ok = False
            except Exception as exc:
                logger.debug("Wave-5 confluence gate error (allow): {}", exc)

        if not confluence_ok:
            return False

        # 3. Rejection filter — anti-signals
        rejection_ok = True
        if hasattr(self, "_wave5_rejection") and self._wave5_rejection is not None:
            try:
                allowed, reason, details = self._wave5_rejection.evaluate(
                    signal=signal.to_dict(),
                    context={
                        "current_spread_bps": spread_bps,
                        "open_positions": open_positions or [],
                        "current_ts": datetime.now(IST),
                        "trade_date": today,
                    },
                )
                if not allowed:
                    self._wave5_rejection.log_rejection(signal.to_dict(), reason, details)
                    logger.info(
                        "Wave-5 rejection filter blocked %s: %s",
                        signal.strategy_name,
                        reason,
                    )
                    rejection_ok = False
            except Exception as exc:
                logger.debug("Wave-5 rejection gate error (allow): {}", exc)

        return rejection_ok
