"""Utility modules for the trading bot."""

from src.utils.exceptions import (
    AuthenticationError,
    InstrumentError,
    InsufficientMarginError,
    OrderError,
    RateLimitError,
    RiskLimitBreachedError,
    TokenExpiredError,
    TradingBotError,
    WebSocketError,
)
from src.utils.health_monitor import (
    ComponentHealth,
    ComponentNotHealthyError,
    ComponentStatus,
    HealthMonitor,
    MemoryMonitor,
    get_health_monitor,
    require_healthy,
)
from src.utils.helpers import (
    format_instrument_key,
    is_market_open,
    now_ist,
    paisa_to_rupees,
    parse_time,
    rupees_to_paisa,
)
from src.utils.logger import logger, setup_logger
from src.utils.rate_limiter import RateLimiter
from src.utils.scheduler import TaskScheduler
from src.utils.validation import (
    ConfigValidationModel,
    InputValidator,
    OrderValidationModel,
    SignalValidationModel,
    ValidationError,
    ValidationResult,
    get_sanitized_symbol,
    is_valid_price,
    is_valid_quantity,
    is_valid_symbol,
    sanitize_numeric,
    sanitize_symbol,
    sanitize_timestamp,
    validate_inputs,
)

__all__ = [
    "AuthenticationError",
    "ComponentHealth",
    "ComponentNotHealthyError",
    "ComponentStatus",
    "ConfigValidationModel",
    "HealthMonitor",
    "InstrumentError",
    "InsufficientMarginError",
    "InputValidator",
    "MemoryMonitor",
    "OrderError",
    "OrderValidationModel",
    "RateLimitError",
    "RateLimiter",
    "RiskLimitBreachedError",
    "SignalValidationModel",
    "TaskScheduler",
    "TokenExpiredError",
    "TradingBotError",
    "ValidationError",
    "ValidationResult",
    "WebSocketError",
    "format_instrument_key",
    "get_health_monitor",
    "get_sanitized_symbol",
    "is_market_open",
    "is_valid_price",
    "is_valid_quantity",
    "is_valid_symbol",
    "logger",
    "now_ist",
    "paisa_to_rupees",
    "parse_time",
    "require_healthy",
    "rupees_to_paisa",
    "sanitize_numeric",
    "sanitize_symbol",
    "sanitize_timestamp",
    "setup_logger",
    "validate_inputs",
]
